import React, { useState } from 'react';
import { 
  FolderTree, 
  Folder, 
  FileText, 
  Download, 
  Copy, 
  Check, 
  ShieldCheck, 
  Search, 
  Sparkles, 
  Terminal, 
  X, 
  FileCode, 
  HardDrive, 
  Layers, 
  Building2, 
  Scale, 
  Receipt, 
  Compass,
  FileCheck2,
  Share2
} from 'lucide-react';
import { 
  GOOGLE_DRIVE_PROJECT_SEED_TREE, 
  MASTER_PROJECT_LOG_CONTENT, 
  HYPATIA_SOURCE_ROOT,
  DriveFolderNode, 
  DriveFileItem 
} from '../data/projectSourceDriveTree';

interface ProjectSourceDriveModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAskHypatia?: (prompt: string) => void;
}

export const ProjectSourceDriveModal: React.FC<ProjectSourceDriveModalProps> = ({
  isOpen,
  onClose,
  onAskHypatia,
}) => {
  const [selectedFilter, setSelectedFilter] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [activeFolderId, setActiveFolderId] = useState<string>(GOOGLE_DRIVE_PROJECT_SEED_TREE[0]?.id || '');
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [showGithubAdvice, setShowGithubAdvice] = useState<boolean>(false);

  if (!isOpen) return null;

  const filters = [
    { id: 'all', name: 'كافة المجلدات', icon: Layers, count: GOOGLE_DRIVE_PROJECT_SEED_TREE.length },
    { id: 'قرارات', name: 'القرارات', icon: Compass, count: GOOGLE_DRIVE_PROJECT_SEED_TREE.filter(f => f.subType === 'قرارات').length },
    { id: 'عقود', name: 'العقود', icon: Scale, count: GOOGLE_DRIVE_PROJECT_SEED_TREE.filter(f => f.subType === 'عقود').length },
    { id: 'عروض', name: 'العروض والمشتريات', icon: Receipt, count: GOOGLE_DRIVE_PROJECT_SEED_TREE.filter(f => f.subType === 'عروض').length },
    { id: 'مشروعات', name: 'منظومة مشاوير والمقر', icon: Building2, count: GOOGLE_DRIVE_PROJECT_SEED_TREE.filter(f => f.category === 'مشروعات ومنظومات').length },
    { id: 'أبحاث', name: 'كاجل والبحث', icon: Sparkles, count: GOOGLE_DRIVE_PROJECT_SEED_TREE.filter(f => f.category === 'أبحاث كاجل والبروتوكول').length },
  ];

  const filteredFolders = GOOGLE_DRIVE_PROJECT_SEED_TREE.filter(folder => {
    let matchesFilter = true;
    if (selectedFilter === 'قرارات') matchesFilter = folder.subType === 'قرارات';
    else if (selectedFilter === 'عقود') matchesFilter = folder.subType === 'عقود';
    else if (selectedFilter === 'عروض') matchesFilter = folder.subType === 'عروض';
    else if (selectedFilter === 'مشروعات') matchesFilter = folder.category === 'مشروعات ومنظومات';
    else if (selectedFilter === 'أبحاث') matchesFilter = folder.category === 'أبحاث كاجل والبروتوكول';

    const matchesQuery = 
      folder.folderName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      folder.displayName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      folder.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      folder.suggestedFiles.some(f => f.name.toLowerCase().includes(searchQuery.toLowerCase()));

    return matchesFilter && matchesQuery;
  });

  const activeFolder = GOOGLE_DRIVE_PROJECT_SEED_TREE.find(f => f.id === activeFolderId) || filteredFolders[0];

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2500);
  };

  const handleDownloadMasterLog = () => {
    const blob = new Blob([MASTER_PROJECT_LOG_CONTENT], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'MASTER_HYPATIA_SOURCE_LOG_2026.md';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadBatchWindows = () => {
    // Generates Windows batch script to create Hypatia_Source tree
    const batchCommands = GOOGLE_DRIVE_PROJECT_SEED_TREE.map(f => `mkdir "${f.path.replace(/\//g, '\\')}"`).join('\r\n');
    const fullScript = `@echo off\r\nchcp 65001 > nul\r\nREM Script generated by Hypatia for Eng. Sameh Yassin\r\nREM Creates Google Drive / Hypatia_Source Folder Tree\r\necho ====================================================\r\necho Creating Google Drive Root: ${HYPATIA_SOURCE_ROOT}...\r\necho ====================================================\r\n${batchCommands}\r\necho.\r\necho All folders under ${HYPATIA_SOURCE_ROOT} created successfully!\r\npause`;
    
    const blob = new Blob([fullScript], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'create_hypatia_source_tree.bat';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadBashLinux = () => {
    // Generates Linux/Mac shell script
    const shellCommands = GOOGLE_DRIVE_PROJECT_SEED_TREE.map(f => `mkdir -p "${f.path}"`).join('\n');
    const fullScript = `#!/usr/bin/env bash\n# Script generated by Hypatia for Eng. Sameh Yassin\n# Creates Google Drive / Hypatia_Source Folder Tree\necho "Creating Google Drive Root: ${HYPATIA_SOURCE_ROOT}..."\n${shellCommands}\necho "All folders under ${HYPATIA_SOURCE_ROOT} created successfully!"\n`;

    const blob = new Blob([fullScript], { type: 'text/x-shellscript;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'create_hypatia_source_tree.sh';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2.5 sm:p-4 bg-slate-950/65 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl border border-slate-200 shadow-2xl w-full max-w-5xl h-[92vh] flex flex-col overflow-hidden text-slate-800">
        
        {/* Top Header Bar: Web3 Sleek Styling */}
        <div className="px-5 py-4 bg-gradient-to-r from-slate-950 via-slate-900 to-indigo-950 text-white flex items-center justify-between shrink-0 shadow-sm border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-teal-400 via-cyan-400 to-indigo-400 text-slate-950 flex items-center justify-center font-bold shadow-lg shadow-teal-500/20">
              <HardDrive className="w-5 h-5 text-slate-950 stroke-[2.2px]" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-sm sm:text-base font-black tracking-wide font-sans">
                  مستودع المزامنة السحابي • {HYPATIA_SOURCE_ROOT}
                </h2>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-teal-400/20 text-teal-300 font-mono font-bold border border-teal-400/30">
                  Google Drive Master
                </span>
              </div>
              <p className="text-[11px] text-slate-300">
                المجلد الرئيسي المعتمد (منظومة مشاوير، 4B، وكالة، دارو، شبكات وعتاد المقر، وعرض WE VPN) والمجلدات الفرعية
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowGithubAdvice(!showGithubAdvice)}
              className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold transition flex items-center gap-1.5 border border-slate-700"
              title="دليل خصوصية وأمان مستودعات GitHub"
            >
              <ShieldCheck className="w-3.5 h-3.5 text-teal-400" />
              <span className="hidden sm:inline">أمان GitHub</span>
            </button>

            <button
              onClick={handleDownloadMasterLog}
              className="px-3 py-1.5 rounded-xl bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-400 hover:to-cyan-400 text-slate-950 text-xs font-bold transition flex items-center gap-1.5 shadow-md shadow-teal-900/30"
              title="تحميل السجل التاريخي الشامل بصيغة Markdown"
            >
              <Download className="w-3.5 h-3.5" />
              <span>تحميل السجل الشامل (MD)</span>
            </button>

            <button
              onClick={onClose}
              className="w-8 h-8 rounded-xl bg-slate-800/80 hover:bg-slate-700 text-slate-400 hover:text-white flex items-center justify-center transition"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* GitHub Security & Privacy Advisory Banner */}
        {showGithubAdvice && (
          <div className="p-4 bg-gradient-to-r from-amber-50 to-orange-50 border-b border-amber-200 text-slate-800 text-xs space-y-2 shrink-0 animate-in slide-in-from-top-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-amber-900 flex items-center gap-1.5 text-sm">
                <ShieldCheck className="w-4 h-4 text-amber-600" />
                توضيح حاسم بخصوص سرية وأمان مستودعات GitHub الخاصة (Private):
              </span>
              <button
                onClick={() => setShowGithubAdvice(false)}
                className="text-amber-800 hover:text-amber-950 font-bold"
              >
                ✕ إغلاق
              </button>
            </div>
            <p className="leading-relaxed text-slate-700">
              يا باشمهندس سامح، <strong>المستودعات الخاصة (Private Repositories) على GitHub مجانية 100% ومغلقة تماماً</strong> أمام العالم ولا يمكن لأحد رؤيتها أو فحصها سواك أنت فقط. لا محركات بحث ولا مستخدمين خارجيين يمكنهم الوصول إليها.
            </p>
          </div>
        )}

        {/* Filter Strip & Fast Action Toolbar */}
        <div className="p-3 bg-slate-50 border-b border-slate-200 flex flex-wrap items-center justify-between gap-2 shrink-0">
          
          {/* Filters: All, Decisions, Contracts, Quotations, Projects, Research */}
          <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar py-0.5 max-w-full">
            {filters.map(f => {
              const Icon = f.icon;
              const isSelected = selectedFilter === f.id;
              return (
                <button
                  key={f.id}
                  onClick={() => setSelectedFilter(f.id)}
                  className={`px-3 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 whitespace-nowrap ${
                    isSelected
                      ? 'bg-slate-900 text-white shadow-sm'
                      : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-100'
                  }`}
                >
                  <Icon className="w-3.5 h-3.5" />
                  <span>{f.name}</span>
                  <span className={`text-[10px] px-1.5 py-0.2 rounded-full font-mono ${
                    isSelected ? 'bg-slate-700 text-teal-300' : 'bg-slate-100 text-slate-500'
                  }`}>
                    {f.count}
                  </span>
                </button>
              );
            })}
          </div>

          {/* Quick Script Downloads & Search Box */}
          <div className="flex items-center gap-2 w-full sm:w-auto">
            <div className="relative flex-1 sm:w-52">
              <Search className="w-3.5 h-3.5 absolute right-3 top-2.5 text-slate-400" />
              <input
                type="text"
                placeholder="بحث في المجلدات أو الملفات..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-3 pr-8 py-1.5 rounded-xl border border-slate-200 text-xs bg-white focus:outline-none focus:ring-2 focus:ring-teal-500"
              />
            </div>

            {/* Script for Windows .bat */}
            <button
              onClick={handleDownloadBatchWindows}
              className="px-2.5 py-1.5 rounded-xl bg-indigo-50 hover:bg-indigo-100 text-indigo-900 border border-indigo-200 text-xs font-bold transition flex items-center gap-1 shrink-0"
              title="تنزيل سكربت لإنشاء مجلد Hypatia_Source وكافة تفرعاته تلقائياً على ويندوز"
            >
              <Terminal className="w-3.5 h-3.5 text-indigo-600" />
              <span>سكربت (.bat)</span>
            </button>

            {/* Script for Mac/Linux .sh */}
            <button
              onClick={handleDownloadBashLinux}
              className="px-2.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-300 text-xs font-bold transition flex items-center gap-1 shrink-0"
              title="تنزيل سكربت لإنشاء مجلد Hypatia_Source وكافة تفرعاته تلقائياً على ماك أو لينكس"
            >
              <Terminal className="w-3.5 h-3.5 text-slate-700" />
              <span>سكربت (.sh)</span>
            </button>
          </div>
        </div>

        {/* Master Body: Folder List (Left/Right) vs Folder Details (Right/Left) */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden bg-slate-100/60">
          
          {/* Folders List Column */}
          <div className="w-full md:w-80 lg:w-96 border-b md:border-b-0 md:border-l border-slate-200 bg-white overflow-y-auto divide-y divide-slate-100 shrink-0">
            <div className="p-2.5 bg-slate-50 text-[11px] font-bold text-slate-500 uppercase tracking-wider flex items-center justify-between border-b border-slate-100">
              <span className="flex items-center gap-1.5">
                <FolderTree className="w-3.5 h-3.5 text-teal-600" />
                <span>المجلدات المتوفرة ({filteredFolders.length})</span>
              </span>
              <span className="text-teal-700 font-mono font-bold text-[10px]">
                {HYPATIA_SOURCE_ROOT}/
              </span>
            </div>

            <div className="p-2 space-y-1">
              {filteredFolders.map(folder => {
                const isSelected = folder.id === activeFolder?.id;
                return (
                  <button
                    key={folder.id}
                    onClick={() => setActiveFolderId(folder.id)}
                    className={`w-full text-right p-3 rounded-2xl transition flex items-start gap-2.5 ${
                      isSelected
                        ? 'bg-gradient-to-r from-teal-50 to-cyan-50 border border-teal-200 text-teal-950 shadow-sm'
                        : 'hover:bg-slate-50 text-slate-700 border border-transparent'
                    }`}
                  >
                    <div className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 ${
                      isSelected 
                        ? 'bg-teal-600 text-white' 
                        : folder.subType === 'عقود' ? 'bg-amber-50 text-amber-700 border border-amber-200'
                        : folder.subType === 'قرارات' ? 'bg-purple-50 text-purple-700 border border-purple-200'
                        : folder.subType === 'عروض' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                        : 'bg-slate-100 text-slate-600'
                    }`}>
                      <Folder className="w-4 h-4 stroke-[2.2px]" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-1">
                        <span className="text-xs font-bold truncate block">
                          {folder.displayName}
                        </span>
                        <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-100 text-slate-600 shrink-0 font-mono">
                          {folder.suggestedFiles.length} ملفات
                        </span>
                      </div>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className={`text-[9px] px-1.5 py-0.2 rounded font-bold ${
                          folder.subType === 'عقود' ? 'bg-amber-100 text-amber-900' :
                          folder.subType === 'قرارات' ? 'bg-purple-100 text-purple-900' :
                          folder.subType === 'عروض' ? 'bg-emerald-100 text-emerald-900' :
                          'bg-slate-100 text-slate-600'
                        }`}>
                          {folder.subType}
                        </span>
                        <span className="text-[10px] text-slate-400 truncate font-mono">
                          {folder.path.replace(`${HYPATIA_SOURCE_ROOT}/`, '')}
                        </span>
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Active Folder Contents & Required Documents */}
          <div className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-4 bg-slate-50/70">
            {activeFolder ? (
              <div className="space-y-4 max-w-3xl">
                
                {/* Active Folder Breadcrumbs & Path Card */}
                <div className="p-4 rounded-3xl bg-white border border-slate-200 shadow-sm space-y-2">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 pb-3">
                    <div className="flex items-center gap-2.5">
                      <div className="w-10 h-10 rounded-2xl bg-teal-50 text-teal-700 border border-teal-200 flex items-center justify-center shrink-0">
                        <Folder className="w-5 h-5" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <h3 className="text-sm sm:text-base font-bold text-slate-900">
                            {activeFolder.displayName}
                          </h3>
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-700 font-bold">
                            {activeFolder.category}
                          </span>
                        </div>
                        <p className="text-xs text-slate-500 mt-0.5">
                          {activeFolder.description}
                        </p>
                      </div>
                    </div>

                    <button
                      onClick={() => handleCopy(activeFolder.path, `path-${activeFolder.id}`)}
                      className="px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold transition flex items-center gap-1.5 self-start sm:self-auto shrink-0 active:scale-95"
                    >
                      {copiedId === `path-${activeFolder.id}` ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-teal-600" />
                          <span>تم نسخ المسار ✓</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5" />
                          <span>نسخ المسار الكامل</span>
                        </>
                      )}
                    </button>
                  </div>

                  <div className="p-2.5 rounded-2xl bg-slate-50 border border-slate-200 text-[11px] font-mono text-slate-700 flex items-center justify-between">
                    <span className="truncate">المسار في Google Drive: <strong>{activeFolder.path}</strong></span>
                  </div>
                </div>

                {/* Suggested Documents in Folder */}
                <div className="space-y-2.5">
                  <div className="flex items-center justify-between">
                    <h4 className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
                      <FileText className="w-4 h-4 text-teal-600" />
                      <span>الملفات والمستندات المخصصة لهذا المجلد ({activeFolder.suggestedFiles.length}):</span>
                    </h4>
                    <span className="text-[10px] text-slate-500">
                      اضغط لنسخ الاسم المقترح للإيداع
                    </span>
                  </div>

                  <div className="space-y-2">
                    {activeFolder.suggestedFiles.map((file) => (
                      <div
                        key={file.id}
                        className="p-3.5 rounded-2xl bg-white border border-slate-200 hover:border-teal-300 transition shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-3"
                      >
                        <div className="flex items-start gap-3">
                          <div className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 mt-0.5 ${
                            file.extension === 'pdf' ? 'bg-red-50 text-red-600' :
                            file.extension === 'md' ? 'bg-indigo-50 text-indigo-600' :
                            file.extension === 'json' ? 'bg-amber-50 text-amber-600' :
                            file.extension === 'apk' ? 'bg-emerald-50 text-emerald-600' :
                            file.extension === 'sql' ? 'bg-blue-50 text-blue-600' :
                            'bg-slate-100 text-slate-600'
                          }`}>
                            <FileCode className="w-4 h-4" />
                          </div>

                          <div>
                            <div className="flex items-center gap-2 flex-wrap">
                              <h5 className="text-xs font-bold text-slate-900">
                                {file.name}
                              </h5>
                              <span className={`text-[9px] px-2 py-0.5 rounded-full font-bold ${
                                file.importance === 'حرج للغاية' ? 'bg-red-100 text-red-800' :
                                file.importance === 'رئيسي' ? 'bg-teal-100 text-teal-800' :
                                'bg-slate-100 text-slate-700'
                              }`}>
                                {file.importance}
                              </span>
                              <span className="text-[9px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-700 font-bold">
                                {file.folderType}
                              </span>
                              <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-slate-100 text-slate-600">
                                .{file.extension}
                              </span>
                            </div>

                            <p className="text-[11px] text-slate-600 mt-1 leading-relaxed">
                              {file.description}
                            </p>

                            <div className="mt-1 text-[10px] font-mono text-slate-500 bg-slate-50 px-2 py-0.5 rounded inline-block border border-slate-200">
                              اسم الملف للإيداع: {file.recommendedFileName}
                            </div>
                          </div>
                        </div>

                        <div className="flex items-center gap-2 self-end sm:self-center shrink-0">
                          <button
                            onClick={() => handleCopy(file.recommendedFileName, `file-${file.id}`)}
                            className="px-2.5 py-1 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold transition flex items-center gap-1"
                            title="نسخ اسم الملف المعتمد"
                          >
                            {copiedId === `file-${file.id}` ? (
                              <>
                                <Check className="w-3 h-3 text-teal-600" />
                                <span>تم النسخ</span>
                              </>
                            ) : (
                              <>
                                <Copy className="w-3 h-3" />
                                <span>نسخ الاسم</span>
                              </>
                            )}
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Consultation with Hypatia */}
                {onAskHypatia && (
                  <div className="p-3.5 rounded-2xl bg-gradient-to-r from-teal-50 via-white to-cyan-50 border border-teal-200 flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-teal-600" />
                      <span className="text-xs text-slate-700 font-medium">
                        هل تريد صياغة أو مراجعة محتوى أي ملف من ملفات {activeFolder.displayName}؟
                      </span>
                    </div>
                    <button
                      onClick={() => {
                        onClose();
                        onAskHypatia(`أريد تجهيز وصياغة ملفات المجلد السحابي: ${activeFolder.path}`);
                      }}
                      className="px-3 py-1 rounded-xl bg-teal-600 hover:bg-teal-500 text-white text-xs font-bold transition shrink-0"
                    >
                      استشارة هيباتيا
                    </button>
                  </div>
                )}

              </div>
            ) : (
              <div className="flex items-center justify-center h-64 text-slate-400 text-xs">
                اختر مجلداً من القائمة الجانبية لعرض محتوياته
              </div>
            )}
          </div>

        </div>

        {/* Footer Bar */}
        <div className="px-5 py-3 bg-white border-t border-slate-200 flex items-center justify-between text-xs text-slate-500 shrink-0">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-teal-500 animate-pulse"></span>
            <span>المجلد الرئيسي: <strong>{HYPATIA_SOURCE_ROOT}</strong> • مهيأ بالكامل للقرارات، العقود، والعروض</span>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold transition"
          >
            إغلاق
          </button>
        </div>

      </div>
    </div>
  );
};
